### ISSUE TITLE
Not waiting for xml http requests and hence before data inside some heavy page is loaded the extension gives the page load time

### ISSUE THREAD

**Issue by taruntalreja08** [alex-vv/page-load-time#15]
You are not waiting for any the xml http requests so before the data is loaded the extension shows the Page Load Time . In a Power BI report, there are many visuals and hence the report load time is also there in which all the data in the visuals load so will the Page Load Time calculated using this extension will yield correct result for such a report ? I used this extension on a Power BI report and I was getting Page Load Time before all the data inside the report was loading. So I wanted to implement this functionality , if this code is not correct according to you also for those reports can you give me some approach using which I can calculate the whole time till report is loaded.

**Comment by alex-vv** [comment]
I am aware of this issue, but it is not very easy to correctly measure load time because there can be periodical ajax requests and in that case page is technically never be fully 'loaded'. There is a similar issue https://github.com/alex-vv/chrome-load-timer/issues/8. I wanted to experiment with this some day but this was a low priority task. Thanks for raising this issue again, I will try to do something this month.

**Comment by taruntalreja08** [comment]
Yes but you can reject some invalid urls which have like this at the end /subscribe, /track, /tokenRefresh, /metadata/models/,/metadata/ping . You can wait for some requests not all . Can you help me implement this in your code?

**Comment by alex-vv** [comment]
Ok I will try to work on it this week. Do you have a publicly accessible URL so I can check your case?

**Comment by taruntalreja08** [comment]
Yes i implemented the same thing and my project is here https://drive.google.com/open?id=0B1-74dRllLIjaEgwWGQxS2VuQnc . I am calculating two load times : one after clearing cache and one with not clearing cache . The problem is I am not able to convert my chrome extension to an edge extension and it does not work in edge due to some incompatibility issues.

**Comment by alex-vv** [comment]
decided not to implement this https://github.com/alex-vv/page-load-time/issues/8#issuecomment-647135561
