### ISSUE TITLE
Consider adding an option to track performance over time per website

### ISSUE THREAD

**Issue by alex-vv** [alex-vv/page-load-time#19]
It could optionally provide additional accumulated statistics per page

**Comment by jadok** [comment]
Hi, I am interrested in this demand.
I will provide something by storing timing data through an array.

**Comment by alex-vv** [comment]
I decided not to implement this as I want to keep this extension simple. There are many possible ways how this feature could look and I think one extension cannot cover all these use cases.

Besides it seems there are already some extensions which do something similar, for example:
https://chrome.google.com/webstore/detail/average-load-time-tester/pflmhongacoepfhkgidighbmppahnljh
