### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by erotavlasme** [alex-vv/page-load-time#25]
Hi,
I found your add on very useful. Do you have plan to port it to firefox?

**Comment by alex-vv** [comment]
Yes, I already added Firefox support for the next version. It is not released yet as I am still working on some new features.

**Comment by alex-vv** [comment]
The latest version is compatible with Firefox and published to https://addons.mozilla.org/, waiting for the review now

**Comment by alex-vv** [comment]
It is available now at https://addons.mozilla.org/en-US/firefox/addon/load-timer/
