### ISSUE TITLE
Deleted from chrome store?

### ISSUE THREAD

**Issue by dyanakiev** [alex-vv/page-load-time#28]
Hello, i reinstalled my chrome browser and now the extension is no longer available in google chrome store, is there a problem with the package?

**Comment by dyanakiev** [comment]
I was able to recover it and installed it like unpacked package so im good for now.

**Comment by JamoCA** [comment]
As a result of Google's action, could you submit your Chrome Extension to Microsoft as an Edge Add-on?
https://microsoftedge.microsoft.com/addons/Microsoft-Edge-Extensions-Home

Here's instructions on how to submit.
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

NOTE: After the new version of Edge was released, I've ceased using Google Chrome on all Windows & iOS devices that I manage.

**Comment by alex-vv** [comment]
The current version is rejected from Chrome store, I am planning to try to submit the new one with a limited permission set once it is ready. This new version also has Firefox support and I am planning to submit it to Firefox addons. 

Regarding Edge, as I don't have Windows machine and I don't use it I am not planning to support it. But if it is fully compatible with Chrome and will work out of box without any code changes then I can submit it there.

**Comment by JamoCA** [comment]
If you don't use Windows, which OS do you use?  If Mac, then you can use Microsoft Edge.  Basically it's the same extension package that you'd use with the Chrome Store, except you wouldn't be dealing with Google and corporate users that are locked in to Microsoft would be able to install it.  (After installing Edge and reviewing it for a couple days, I uninstalled Chrome on every PC that I manage/access.)

I contacted another independent Chrome extension developer that only offered side-loading and he was able to get his extension listed in the Microsoft store. He stated he wasn't able to personally install Edge, but he was still able to publish it in their store.  You can follow that conversation [here](https://github.com/erickutcher/httpdownloader/issues/102).

[PushBullet](https://www.pushbullet.com/) had to jump through some hoops with Google regarding their extension. I hope you have better luck.

- https://blog.pushbullet.com/2020/05/13/lets-guess-what-google-requires-in-14-days-or-they-kill-our-extension
- https://blog.pushbullet.com/2020/05/15/our-extension-is-safe
- https://blog.pushbullet.com/2020/06/08/updating-our-chrome-extension-after-our-google-scare

**Comment by niladam** [comment]
hey @alex-vv i've been affected by the same issue, the extension was removed from my Chrome and got to this thread.

Can you tell us what happened and why the extension was deleted ?

Also, can you maybe keep us updated ? 

If there's anything i/we could do to help maybe ask here and we'll be able to give out a hand ?

Thanks,
Madalin.

**Comment by TheRealJAG** [comment]
Love this extension. Why was it removed?

**Comment by alex-vv** [comment]
I published the latest version to Chrome, Firefox and Edge stores, waiting for the review now.

**Comment by alex-vv** [comment]
It is available now for Firefox: https://addons.mozilla.org/en-US/firefox/addon/load-timer/ 
and Edge: https://microsoftedge.microsoft.com/addons/detail/page-load-time/llcdjocbfkdndmjbgpaibfkdjkjogeho

submission for Chrome store got rejected again :( I will try to investigate if there is some way I could make into it.

**Comment by niladam** [comment]
@alex-vv can you maybe tell us the issues you're encountering ? Maybe we can help.

Also, it could be google just acting like jerks since they launched the PageInsights extension. However, **maybe** some of us can help..

**Comment by alex-vv** [comment]
@niladam they say it does violate user privacy because it doesn't require a minimum set of permissions. I cannot put the exact message because it is in Russian. The message is broad and it doesn't say what exactly they don't like.

I suspect it happens because extension requires permission for all hosts to inject the content script which measures performance. I need to do that to be able to display performance number in a badge without user action. If I just use `activeTab` permission only then it would mean user should click the extension to get the performance numbers for the current page, it won't be available automatically.

This is all very ironic since I don't collect ANY personal information unlike Google itself.

**Comment by niladam** [comment]
Why not use the [same permissions as ublock](https://github.com/gorhill/uBlock/blob/master/platform/chromium/manifest.json) ? Or at least part of them ?

**Comment by niladam** [comment]
@alex-vv or maybe like [**Google's** own extension](https://github.com/google/password-alert/blob/master/chrome/manifest.json) ?

```json

  "permissions": [
    "identity",
    "identity.email",
    "notifications",
    "storage",
    "tabs",
    "<all_urls>"
  ],

```

**Comment by alex-vv** [comment]
yes, I will check and test these

**Comment by dnknn** [comment]
@alex-vv 
https://chrome.google.com/webstore/detail/fploionmjgeclbkemipmkogoaohcdbig
`404` for so long, So, Can you increase the download of `.crx` file on the following page 👇❓	

### [github.com/alex-vv/page-load-time/releases](https://github.com/alex-vv/page-load-time/releases)

![0722074717](https://user-images.githubusercontent.com/10995302/88118188-94113780-cbef-11ea-8265-283754213303.png)

**Comment by pmjcreations** [comment]
Privacy and Google, that's not in sync.

I was using this extension, and I was wondering why the extension was missing.

Since I reduced using Google and Facebook, I am happy with your Edge and Firefox extension.

**Comment by mattonit** [comment]
@alex-vv what's the status of this issue?

**Comment by alex-vv** [comment]
It is back in Chrome Store finally 
https://chrome.google.com/webstore/detail/page-load-time/fploionmjgeclbkemipmkogoaohcdbig
