### ISSUE TITLE
Timings not showing when clicked

### ISSUE THREAD

**Issue by dyanakiev** [alex-vv/page-load-time#30]
![image](https://user-images.githubusercontent.com/11967079/95830453-5e887000-0d40-11eb-93fb-bd88ea17dc6c.png)

I use it in chrome as unpacked extension, any idea why i dont see the values when i click the icon?

**Comment by dyanakiev** [comment]
Nevermind, its working again.

**Comment by gitti0** [comment]
I have exatcly the same problem in Firefox. The screenshot provided by @dyanakiev is the same, blank.

My system is Windows10, Firefox 68ESR, 4k monitor and Intel integrated card.

I tried on another system again Wndows 10, Firefox 68ESR and navigation timmig is properly.

Both setups are with clean Firefox profile and the only extension is the page load time.

@dyanakiev, do you have 4k monitor? What is your setup?
