### ISSUE TITLE
Timing popup seems to be cached

### ISSUE THREAD

**Issue by mlaurense** [alex-vv/page-load-time#32]
The icon in the Chrome toolbar updates its timing when refreshing the page. However, the contents of the popup stay the same across all pages and all open tabs. A cache issue perhaps?

Using version 3.1.1 from Chrome web store on Chrome 86.0.4240.198 Mac

![Schermafbeelding 2020-11-18 om 10 41 35](https://user-images.githubusercontent.com/16759472/99513216-a8d9be00-298a-11eb-9f7e-394e107b058f.png)

**Comment by alex-vv** [comment]
Thanks for reporting, I managed to reproduce it. This happens when several browser windows are opened. Will fix.
