### ISSUE TITLE
Page load time number in Firefox 92.0 is cut

### ISSUE THREAD

**Issue by bbronisz** [alex-vv/page-load-time#36]
![image](https://user-images.githubusercontent.com/1271444/133437029-8b1453a7-db3c-4598-a7f8-1337e1e83bb2.png)
The latest version of Firefox probably limits overflow on icons in toolbar so now it is partially hidden as seen on the above screenshot.

**Comment by alex-vv** [comment]
Unfortunately I cannot control that. Probably for FF I will use one less char so it will be one digit after decimal point in most cases.

**Comment by bbronisz** [comment]
Thanks!
