### ISSUE TITLE
Update to manifest version 3

### ISSUE THREAD

**Issue by alex-vv** [alex-vv/page-load-time#37]
See 
https://blog.chromium.org/2020/12/manifest-v3-now-available-on-m88-beta.html
https://developer.chrome.com/blog/mv2-transition/

**Comment by de-ar** [comment]
Just a quick question. If the extension is only for Chrome, why use browser polyfill?

**Comment by alex-vv** [comment]
This extension is not only for Chrome. Currently I am waiting for Firefox to support manifest v3 
https://bugzilla.mozilla.org/show_bug.cgi?id=1578284

**Comment by de-ar** [comment]
Thanks, and really sorry for assuming that it was only for Chrome.

**Comment by marclaporte** [comment]
I just checked and it appears they (Firefox) are still working on it.
