### ISSUE TITLE
Does not work anymore with Chrome

### ISSUE THREAD

**Issue by r2ixuz** [alex-vv/page-load-time#41]
With latest Chrome Version 111.0.5563.64 this great extension does not work. It shows nothing on click and no little ms number under the icon in the extension bar when a web page is finished with loading.

**Comment by JamoCA** [comment]
That's not good.  By way of contrast, I'm using Microsoft Edge 111.0.1661.41 (dev) and it appears to still be functioning correctly.

**Comment by r2ixuz** [comment]
As this only happens for me on MacOS (Linux works fine) I reinstalled the extension and it is working again. Don't know why this was needed...
