### ISSUE TITLE
A plagiarized extension has been discovered in the Edge store. 

### ISSUE THREAD

**Issue by leafarilongamor** [alex-vv/page-load-time#43]
I'd like to notify you that I've come across an extension resembling page-load-time, lacking any details about its code. 
The extension is called "Tab Timer".

![image](https://github.com/alex-vv/page-load-time/assets/113082111/ee9ed906-fd01-45ae-9412-5983162c0507)

I've reported this to Microsoft for review, as it not only seems to be a case of plagiarism but also potentially harmful.

**Comment by marclaporte** [comment]
Given all the information an extension like this could gather, it is quite a risk indeed.

**Comment by alex-vv** [comment]
So I reported this as well, but got no response so far. Not sure what else I can do at that point, so closing this issue for now.
